eureka:
  instance:
    hostname: localhost
    
    prefer-ip-address: true
    
  client:
    fetch-registry: true
    register-with-eureka: true
    
spring:
  application:
    name: hotel-service
